# Generated by Django

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=apps.users.models.default_user_settings,
                help_text="User UI/UX preferences and encrypted per-user credentials.",
            ),
        ),
    ]
