# Generated by Django 6.1.1 on 2026-09-27 13:53

import apps.journal.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('entry_submitted', 'Entry submitted'), ('entry_edited', 'Entry edited'), ('addendum_added', 'Addendum added'), ('photo_uploaded', 'Photo uploaded'), ('photo_deleted', 'Photo soft-deleted')], max_length=40)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the visit happened, as the author entered it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pain_source', models.CharField(blank=True, choices=[('travis_said', 'Travis said'), ('observed', 'Observed')], max_length=20)),
                ('trend', models.CharField(blank=True, choices=[('better', 'Better than last time'), ('same', 'About the same'), ('worse', 'Worse than last time'), ('unsure', 'Not sure / first visit')], max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('questionnaire_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='journal.entry')),
            ],
            options={
                'verbose_name_plural': 'addenda',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='journal.entry')),
            ],
            options={
                'ordering': ['edited_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=255)),
                ('original', models.FileField(upload_to=apps.journal.models.original_upload_to)),
                ('display', models.FileField(upload_to=apps.journal.models.display_upload_to)),
                ('thumb', models.FileField(upload_to=apps.journal.models.thumb_upload_to)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('mime', models.CharField(max_length=100)),
                ('exif_taken_at', models.DateTimeField(blank=True, null=True)),
                ('client_last_modified', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('body_area', models.CharField(choices=[('bruising', 'Bruising'), ('road_rash', 'Road rash'), ('knee_brace', 'Knee / brace'), ('shoulder', 'Shoulder'), ('ribs', 'Ribs'), ('other', 'Other injury'), ('general', 'General / whole visit')], default='general', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=500)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='journal.entry')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
